### ISSUE TITLE
Allow for detecting missing field vs field set to null

### ISSUE THREAD

**Issue by Hackder** [lpil/decode#13]
When working with PATCH requests, you have three cases:
1. The user doesn't specify the field - don't do anything
2. The user does specify the field but sets it to null - set the field to null
3. The user does specify the field with a valid value - set the field to that value

Currently, there is not an easy way of decoding this, both with decode and with decode/zero

In Toy, I solve this by having two functions:
`field` - guarantees that the field is present, and the value from that field is passed to the next decoder
`optional_field` - decodes to `Option(..)`. If the field is present passes the value to the next decoder and returns `Some(what the next decoder returned)`, if the field is missing return `None`

In `decode/zero` this could look something like this:

```gleam
import decode/zero
import gleam/json
import gleam/option.{type Option, None, Some}
import gleam/string

pub type UpdateUser {
  UpdateUser(username: Option(Option(String)), email: Option(Option(String)))
}

pub fn main() {
  let decoder = {
    use username <- zero.optional_field("username", zero.optional(zero.string))
    use email <- zero.optional_field("email", zero.optional(zero.string))
    zero.success(UpdateUser(username:, email:))
  }

  let assert Ok(UpdateUser(username: Some(Some("Thomas")), email: None)) =
    "{ 'username': 'Thomas' }"
    |> string.replace(each: "'", with: "\"")
    |> json.decode(zero.run(_, decoder))

  let assert Ok(UpdateUser(username: None, email: None)) =
    "{  }"
    |> string.replace(each: "'", with: "\"")
    |> json.decode(zero.run(_, decoder))

  let assert Ok(UpdateUser(username: Some(None), email: None)) =
    "{ 'username': null }"
    |> string.replace(each: "'", with: "\"")
    |> json.decode(zero.run(_, decoder))

  let assert Error(_) =
    "{ 'username': 1 }"
    |> string.replace(each: "'", with: "\"")
    |> json.decode(zero.run(_, decoder))
}
```

Points for discussion:
From what I can see, currently `zero` uses the `decode/zero.at` function for both `field` and `subfield`. I am not sure if we should add optional variants for all of these, or how to handle it nicely. In Toy, we have optional variants for `field` and `subfield`, I found this solution to be the easiest to understand and most consistent, though I am open to suggestions.

**Comment by lpil** [comment]
Thank you!

**Comment by sz3lbi** [comment]
On the Discord server, @giacomocavalieri came up with the following solution to a similar question I asked:
```gleam
fn or_none(decoder) {
  zero.one_of(zero.map(decoder, Some), or: [zero.success(None)])
}

pub fn main() {
  let decoder = {
    use username <- zero.then(zero.at("username", zero.optional(zero.string)) |> or_none)
    use email <- zero.then(zero.at("email", zero.optional(zero.string)) |> or_none)
    zero.success(UpdateUser(username:, email:))
  }

  // ...
}
```
If I understand correctly, it should do what you need, but it's certainly not the most straightforward solution to the problem.

**Comment by giacomocavalieri** [comment]
No, this doesn't solve the problem: as things are it's not possible to tell the difference between a field not being there or a field having a `null`/`nil` value. For example:
```gleam
let decoder = zero.at("name", zero.optional(zero.string)) |> or_none

let assert Ok(result) = "{ \"name\": null }" |> json.decode(decoder)
// -> result = Some(None)

let assert Ok(result) = "{}" |> json.decode(decoder)
// -> result = Some(None)
```

**Comment by ryanmiville** [comment]
This ugly workaround seems to work

```gleam
pub fn optional_field(
  field_name: name,
  field_decoder: Decoder(t),
  next: fn(Option(t)) -> Decoder(final),
) -> Decoder(final) {
  let decoding_function = fn(data: Dynamic) {
    use <- bool.guard(dynamic.classify(data) == "Nil", Ok(None))

    case zero.run(data, zero.optional(field_decoder)) {
      Ok(None) -> {
        case zero.run(data, field_decoder) {
          Ok(v) -> Ok(Some(v))
          Error(_) -> Ok(None)
        }
      }
      other -> other
    }
  }

  let decoder = zero.new_primitive_decoder(decoding_function, None)

  zero.field(field_name, decoder, next)
}
```
