### ISSUE TITLE
How to create Dynamic from a record

### ISSUE THREAD

**Issue by julywind168** [lpil/decode#18]
```gleam
pub type User {
  User(name: String, email: String)
}

pub fn decode_test() {
  let decoder = {
    use name <- zero.field("name", zero.string)
    use email <- zero.field("email", zero.string)
    zero.success(User(name:, email:))
  }

  let data = dynamic.from(User("abc", "123"))
  zero.run(data, decoder) |> io.debug
}

// out: Error([DecodeError("Dict", "Tuple of 3 elements", []), DecodeError("Dict", "Tuple of 3 elements", [])])
```

**Comment by lpil** [comment]
The dynamic type is about runtime properties of data, it is not a tool for working with Gleam data more generally and will not be able to work with data which doesn't have the desired runtime properties. You are here successfully converting the record to `Dynamic` but that's not a compatible decoder for the record, and records have different runtime representation on Erlang and on JavaScript so it's non-trivial to abstract over both targets.

What problem are you looking to solve here?

**Comment by julywind168** [comment]
> The dynamic type is about runtime properties of data, it is not a tool for working with Gleam data more generally and will not be able to work with data which doesn't have the desired runtime properties. You are here successfully converting the record to `Dynamic` but that's not a compatible decoder for the record, and records have different runtime representation on Erlang and on JavaScript so it's non-trivial to abstract over both targets.
> 
> What problem are you looking to solve here?

```gleam
           let assert bson.Document(doc) = value
          // let decoder =
          //   dynamic.decode6(
          //     User,
          //     dynamic.field("id", decoders.string),
          //     dynamic.field("account", decoders.string),
          //     dynamic.field("password", decoders.string),
          //     dynamic.field("nickname", decoders.string),
          //     dynamic.field("gold", decoders.int),
          //     dynamic.field("diamond", decoders.int),
          //   )
          let decoder = {
            use account <- zero.field("account", zero.string)
            use password <- zero.field("password", zero.string)
            use id <- zero.field("id", zero.string)
            use nickname <- zero.field("nickname", zero.string)
            use gold <- zero.field("gold", zero.int)
            use diamond <- zero.field("diamond", zero.int)
            zero.success(User(
              account:,
              password:,
              id:,
              nickname:,
              gold:,
              diamond:,
            ))
          }
          case bison.to_custom_type(doc, zero.run(_, decoder)) {
            Ok(user) -> Ok(user)
            Error(err) -> Error(error.DecodeError(string.inspect(err)))
          }
```
Indeed, I have a specific concern。the dynamic.decode6 is work ok, but `bison.to_custom_type(doc, zero.run(_, decoder))` gei me `Error(DecodeError("[DecodeError("String", "Tuple of 2 elements", ["account"]), DecodeError("String", "Tuple of 2 elements", ["password"]), DecodeError("String", "Tuple of 2 elements", ["id"]), DecodeError("String", "Tuple of 2 elements", ["nickname"]), DecodeError("Int", "Tuple of 2 elements", ["gold"]), DecodeError("Int", "Tuple of 2 elements", ["diamond"])]"))`

I try to understand record decoding, readme page show the record decoder, but missing construction of data。  so i try `dynamic.from(User("abc", "123"))` 

Now it seems that I am unable to create Dynamic(decode able) of Record using Gleam

**Comment by lpil** [comment]
You are successfully creating a dynamic value from a record, but you have not written a decoder that accepts that record.

You should never be converting known data into `Dynamic` and then attempting to decode it. You will need to see the documentation for That function to determine what runtime structure the bison library is using.
