### ISSUE TITLE
Decode/zero cannot decode a JS object as a dict

### ISSUE THREAD

**Issue by jimmernauts** [lpil/decode#22]
Repro here:
https://github.com/jimmernauts/repro_20240912

Given a JS object like this:
`{ "name": "John", "age": 30, "address": { "0": "123 Main St", "1": "Anytown", "2": "CA", "3": "12345" } }`
decode/zero errors with: `Error([DecodeError(expected: "Dict", found: "Object", path: ["address"])])`
decode succeeds: `Ok(Person(name: "John", age: 30, address: dict.from_list([#(0, "123 Main St"), #(2, "CA"), #(1, "Anytown"), #(3, "12345")])))`

**Comment by lpil** [comment]
Thank you
