### ISSUE TITLE
It would be nice to have a helper for handling recursive data types

### ISSUE THREAD

**Issue by Acepie** [lpil/decode#3]
I was testing this out and needed to create a decoder for a recursive data type. I first tried writing the seemingly obvious version before realizing it would make an infinite loop.

```gleam
pub type Item {
  Item(id: String, items: option.Option(List(Item)))
}

fn item_decoder() {
  decode.into({
    use id <- decode.parameter
    use items <- decode.parameter
    Item(id, items)
  })
  |> decode.field("id", decode.string)
  |> decode.field(
    "items",
    decode.optional(decode.list(
      item_decoder()
    )),
  )
}
```

Instead I had to write the below version to wrap the nested decoder in a function. This worked but was unintuitive and doesn't really display the intent/reason well. It would be nice to have some sort of helper for this. Maybe "decode.lazy" or something that takes in a function that outputs a decoder

```gleam
pub type Item {
  Item(id: String, items: option.Option(List(Item)))
}

fn item_decoder() {
  decode.into({
    use id <- decode.parameter
    use items <- decode.parameter
    Item(id, items)
  })
  |> decode.field("id", decode.string)
  |> decode.field(
    "items",
    decode.optional(decode.list(
      decode.dynamic |> decode.then(fn(_) { item_decoder() }),
    )),
  )
}
```

**Comment by lpil** [comment]
Yes, for sure! Thank you!

I wonder if we should remove the custom type wrapper due to this 🤔

**Comment by lpil** [comment]
Closing as we'll be moving ahead with the zero API. Thank you
