### ISSUE TITLE
lazy decode doesn't work in javascript target

### ISSUE THREAD

**Issue by dinkelspiel** [lpil/decode#5]
The solution for recursive types in issue #3 doesn't work in the javascript target and instead returns a `TypeError: decoder.continuation is not a function` in the javascript console. The offending compiled code is the code below
```js
function then$2(decoder, next) {
  return new Decoder(
    (d) => {
      let $ = decoder.continuation(d); // Error occurs here
      if ($.isOk()) {
        let a2 = $[0];
        let _pipe = next(a2);
        return from2(_pipe, d);
      } else {
        let e = $[0];
        return new Error(e);
      }
    }
  );
}
```
I don't know wether this is a gleam compiler error or decode library error as the same code works well in the erlang target.

**Comment by lpil** [comment]
Could you share your code please 🙏 thank you

**Comment by lpil** [comment]
Closing due to lack of information in the report.
