### ISSUE TITLE
decode.dynamic throws type error

### ISSUE THREAD

**Issue by RGBboy** [lpil/decode#7]
When I run the following test on a javascript target:

```
pub fn decode_dynamic_test() {
  let value = dynamic.from("testing")
  let output =
    decode.dynamic
    |> decode.from(value)
  should.equal(output, Ok(value))
}
```

I get the following error:

```
TypeError: decoder.continuation is not a function
```

If I change [this line](https://github.com/lpil/decode/blob/3f615917649942da0b2ff85a6efd01cb1574cd99/src/decode.gleam#L526) from:

```
pub const dynamic: Decoder(Dynamic) = Decoder(continuation: Ok)
```

to:

```
pub const dynamic: Decoder(Dynamic) = Decoder(continuation: dynamic.dynamic)
```

it works as expected and the test passes.

I'm a little confused as to why this fixes the problem as they seem to be functionally equivalent...

I'm running gleam 1.4.0 in a Deno environment.

**Comment by RGBboy** [comment]
I just saw someone has created PR #6 that addresses this problem.

**Comment by lpil** [comment]
Thank you. This compiler bug has been fixed
